/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import HAS_A.Website;
import MainAndSys.deviceSys;
import java.util.ArrayList;

/**
 *
 * @author osman
 */
public class AddFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddFrame
     */
    public ArrayList<Website> w = new ArrayList<>();
    MainFrame mf = new MainFrame();
    public AddFrame(MainFrame m) {
        initComponents();
        mf = m;
        laptoppanel.setVisible(false);
        tvpanel.setVisible(false);
        refpanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nametf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        constf = new javax.swing.JTextField();
        nextbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        webnametf = new javax.swing.JTextField();
        webpricetf = new javax.swing.JTextField();
        addwbtn = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();
        typePanel = new javax.swing.JPanel();
        tvpanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        yesbtn = new javax.swing.JRadioButton();
        nobtn = new javax.swing.JRadioButton();
        refpanel = new javax.swing.JPanel();
        energytf = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        laptoppanel = new javax.swing.JPanel();
        ramtf = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        memorytf = new javax.swing.JTextField();
        gamepc = new javax.swing.JRadioButton();
        notbtn = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        truebox = new javax.swing.JCheckBox();
        typecb = new javax.swing.JComboBox<>();
        falsebox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Which type of device do you want to add?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 11, 246, -1));

        jLabel2.setText("Device Name & Brand");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel3.setText("Second Hand?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        getContentPane().add(nametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 72, -1));

        jLabel4.setText("Avg Daily Consumption");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));
        getContentPane().add(constf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 149, -1));

        nextbtn.setText("Next Step");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 113, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 290, 235, 90));

        jLabel7.setText("Enter website name: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel8.setText("Enter price in the website:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));
        getContentPane().add(webnametf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 149, -1));
        getContentPane().add(webpricetf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 63, -1));

        addwbtn.setText("ADD WEBSITE");
        addwbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addwbtnActionPerformed(evt);
            }
        });
        getContentPane().add(addwbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        closebtn.setText("CLOSE");
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        getContentPane().add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 360, -1, -1));

        typePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Is TV Smart?");

        yesbtn.setText("Yes");

        nobtn.setText("No");

        javax.swing.GroupLayout tvpanelLayout = new javax.swing.GroupLayout(tvpanel);
        tvpanel.setLayout(tvpanelLayout);
        tvpanelLayout.setHorizontalGroup(
            tvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(yesbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nobtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tvpanelLayout.setVerticalGroup(
            tvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tvpanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(tvpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(yesbtn)
                    .addComponent(nobtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        typePanel.add(tvpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        jLabel5.setText("Energy Class? ");

        javax.swing.GroupLayout refpanelLayout = new javax.swing.GroupLayout(refpanel);
        refpanel.setLayout(refpanelLayout);
        refpanelLayout.setHorizontalGroup(
            refpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, refpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(energytf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        refpanelLayout.setVerticalGroup(
            refpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(refpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(refpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(energytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        typePanel.add(refpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 190, -1));

        jLabel10.setText("RAM");

        jLabel11.setText("Memory");

        memorytf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memorytfActionPerformed(evt);
            }
        });

        gamepc.setText("Yes");

        notbtn.setText("No");

        jLabel12.setText("Game PC?");

        javax.swing.GroupLayout laptoppanelLayout = new javax.swing.GroupLayout(laptoppanel);
        laptoppanel.setLayout(laptoppanelLayout);
        laptoppanelLayout.setHorizontalGroup(
            laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
            .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(laptoppanelLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(laptoppanelLayout.createSequentialGroup()
                            .addGap(38, 38, 38)
                            .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ramtf, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addComponent(memorytf)))
                        .addGroup(laptoppanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(gamepc)
                            .addGap(18, 18, 18)
                            .addComponent(notbtn)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        laptoppanelLayout.setVerticalGroup(
            laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(laptoppanelLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(ramtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(memorytf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(laptoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(gamepc)
                        .addComponent(notbtn))
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        typePanel.add(laptoppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 210, 180));

        getContentPane().add(typePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 430, 210));

        buttonGroup2.add(truebox);
        truebox.setText("Yes");
        getContentPane().add(truebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        typecb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Television", "Refrigerator", "Laptop" }));
        typecb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typecbActionPerformed(evt);
            }
        });
        getContentPane().add(typecb, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        falsebox.setText("No");
        getContentPane().add(falsebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        if(constf.getText().equalsIgnoreCase("")||nametf.getText().equalsIgnoreCase("")||truebox.isSelected()||falsebox.isSelected()){
            if(w.isEmpty()){
                jTextArea1.setText("Please enter at least 1 website!");
            }
            else{
            if (typecb.getSelectedItem().toString().equalsIgnoreCase("Television")){
                deviceSys.addTv(yesbtn.isSelected(),w,nametf.getText(),truebox.isSelected(),Integer.parseInt(constf.getText()));
                w = new ArrayList<Website>();
                jTextArea1.setText("");
                nametf.setText("");
                constf.setText("");
                truebox.setSelected(false);
                falsebox.setSelected(false);
            }
            else if(typecb.getSelectedItem().toString().equalsIgnoreCase("Laptop")){
                deviceSys.addLaptop(Double.parseDouble(ramtf.getText()),Double.parseDouble(memorytf.getText()),gamepc.isSelected(),w,nametf.getText(),truebox.isSelected(),Integer.parseInt(constf.getText()));
                w = new ArrayList<Website>();
                jTextArea1.setText(""); 
                nametf.setText("");
                constf.setText("");
                truebox.setSelected(false);
                falsebox.setSelected(false);
            }
            else if(typecb.getSelectedItem().toString().equalsIgnoreCase("Refrigerator")){
                deviceSys.addRefrigerator(energytf.getText(),w,nametf.getText(),truebox.isSelected(),Integer.parseInt(constf.getText()));
                w = new ArrayList<Website>();
                jTextArea1.setText("");
                nametf.setText("");
                constf.setText("");
                truebox.setSelected(false);
                falsebox.setSelected(false);
            }
            else{
                jTextArea1.setText("Please select the device type!");
            }
                jTextArea1.setText("");
            }
            
        }
        else
             jTextArea1.setText("Please fill the necessary fields!");
       
    }//GEN-LAST:event_nextbtnActionPerformed

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        mf.setVisible(true);
        dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    private void memorytfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memorytfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_memorytfActionPerformed

    private void addwbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addwbtnActionPerformed
       
        if (webnametf.getText().isEmpty() || webpricetf.getText().isEmpty()) {
            jTextArea1.setText("Do not leave empty website field.");
        } else {
             String name = webnametf.getText();
            double price = Double.parseDouble(webpricetf.getText());
            w.add(new Website(name, price));
            jTextArea1.setText("Website is added!!");
            webnametf.setText("");
            webpricetf.setText("");
        }
    }//GEN-LAST:event_addwbtnActionPerformed

    private void typecbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typecbActionPerformed
        if(typecb.getSelectedItem().toString().equalsIgnoreCase("Television")){
            laptoppanel.setVisible(false);
            tvpanel.setVisible(true);
            refpanel.setVisible(false);
        }
        else if(typecb.getSelectedItem().toString().equalsIgnoreCase("Laptop")){
            laptoppanel.setVisible(true);
            tvpanel.setVisible(false);
            refpanel.setVisible(false);
        }
        else{
            laptoppanel.setVisible(false);
            tvpanel.setVisible(false);
            refpanel.setVisible(true);
        }
    }//GEN-LAST:event_typecbActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addwbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton closebtn;
    private javax.swing.JTextField constf;
    private javax.swing.JTextField energytf;
    private javax.swing.JCheckBox falsebox;
    private javax.swing.JRadioButton gamepc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel laptoppanel;
    private javax.swing.JTextField memorytf;
    private javax.swing.JTextField nametf;
    private javax.swing.JButton nextbtn;
    private javax.swing.JRadioButton nobtn;
    private javax.swing.JRadioButton notbtn;
    private javax.swing.JTextField ramtf;
    private javax.swing.JPanel refpanel;
    private javax.swing.JCheckBox truebox;
    private javax.swing.JPanel tvpanel;
    private javax.swing.JPanel typePanel;
    private javax.swing.JComboBox<String> typecb;
    private javax.swing.JTextField webnametf;
    private javax.swing.JTextField webpricetf;
    private javax.swing.JRadioButton yesbtn;
    // End of variables declaration//GEN-END:variables
}
